# Copyright (c) 2013-2016 SUSE LLC
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of version 3 of the GNU General Public License as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.   See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, contact SUSE LLC.
#
# To contact SUSE about this file by physical or electronic mail,
# you may find current contact information at www.suse.com

require_relative "../tools/helper_builder"

task :default => "try_build"

HELPER_DIR = File.expand_path(File.dirname(__FILE__))

desc "Build the helper if needed"
task :build do
  helper_builder = HelperBuilder.new(HELPER_DIR)
  raise "Error: Build of Machinery helper failed" if !helper_builder.run_build
end

desc "Don't fail on build errors"
task :try_build do
  helper_builder = HelperBuilder.new(HELPER_DIR)
  helper_builder.run_build
end
